name: Update Referencial
on:
  schedule:
    - cron: '0 16,22 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update data
        run: |
         ./update_referencial.py --upload
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      - name: Commit and push if it changed
        run: |
          git config --global user.name "actions-bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || (git commit -m "Update data" && git push)
